//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BACSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BACSI()
        {
            this.CT_HSBA = new HashSet<CT_HSBA>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public int MABS { get; set; }
        [DisplayName ("Tên Bác Sĩ")]
        public string TENBS { get; set; }
        [DisplayName("Ngày Sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NGAYSINHBS { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string SDTBS { get; set; }
        [DisplayName("Địa Chỉ")]
        public string DIACHIBS { get; set; }
        [DisplayName("Chuyên Môn")]
        public string CHUYENMON { get; set; }
        [DisplayName("Trình Độ")]
        public string TRINHDO { get; set; }
        [DisplayName("Ảnh Bác Sĩ")]
        public string ANHBS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HSBA> CT_HSBA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
