//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BANKECHIPHI
    {
        public int MABKCP { get; set; }
        public int MAHSBA { get; set; }
        [DisplayName ("Ngày Lập")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NGAYLAPBKCP { get; set; }
        [DisplayName("Tiền Tạm Ứng")]
        public int TIENTAMUNG { get; set; }
        [DisplayName("Tiền Đóng Thêm")]
        public Nullable<int> TIENDONGTHEM { get; set; }
    
        public virtual HSBA HSBA { get; set; }
    }
}
