//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKECHIPHI
    {
        public int MABKCP { get; set; }
        public int MAHSBA { get; set; }
        public System.DateTime NGAYLAPBKCP { get; set; }
        public int TIENTAMUNG { get; set; }
        public Nullable<int> TIENDONGTHEM { get; set; }
    
        public virtual HSBA HSBA { get; set; }
    }
}
