//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.HSBAs = new HashSet<HSBA>();
        }
    
        public int MABN { get; set; }
        [DisplayName ("Tên Bệnh Nhân")]
        public string TENBN { get; set; }
        [DisplayName("Ngày Sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NGAYSINHBN { get; set; }
        [DisplayName("Địa Chỉ")]
        public string DIACHIBN { get; set; }
        [DisplayName("Giới Tính")]
        public string GIOITINH { get; set; }
        [DisplayName("CMND")]
        public string CMND { get; set; }
        [DisplayName("BHYT")]
        public string BHYT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HSBA> HSBAs { get; set; }
    }
}
