//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CT_TOATHUOC
    {
        public int MATOATHUOC { get; set; }
        public int MATHUOC { get; set; }
        [DisplayName ("Số Lượng")]
        public int SOLUONG { get; set; }
        [DisplayName("Liều Dùng")]
        public string LIEUDUNG { get; set; }
    
        public virtual THUOC THUOC { get; set; }
        public virtual TOATHUOC TOATHUOC { get; set; }
    }
}
