//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.BANKEDICHVUs = new HashSet<BANKEDICHVU>();
        }
        [DisplayName ("Mã Dịch Vụ")]
        public int MADV { get; set; }
        [DisplayName("Tên Dịch Vụ")]
        public string TENDV { get; set; }
        [DisplayName("Đơn Giá")]
        public int DONGIADV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKEDICHVU> BANKEDICHVUs { get; set; }
    }
}
