//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBNKMEntities : DbContext
    {
        public QLBNKMEntities()
            : base("name=QLBNKMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BACSI> BACSIs { get; set; }
        public virtual DbSet<BANKECHIPHI> BANKECHIPHIs { get; set; }
        public virtual DbSet<BANKEDICHVU> BANKEDICHVUs { get; set; }
        public virtual DbSet<BENH> BENHs { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<CT_HSBA> CT_HSBA { get; set; }
        public virtual DbSet<CT_TOATHUOC> CT_TOATHUOC { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HSBA> HSBAs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<TOATHUOC> TOATHUOCs { get; set; }
    }
}
