//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int MATK { get; set; }
        public bool ADMIN { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public int MABS { get; set; }
    
        public virtual BACSI BACSI { get; set; }
    }
}
