//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOATHUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOATHUOC()
        {
            this.CT_TOATHUOC = new HashSet<CT_TOATHUOC>();
        }
    
        public int MATOATHUOC { get; set; }
        public int MAHSBA { get; set; }
        public System.DateTime NGAYKE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TOATHUOC> CT_TOATHUOC { get; set; }
        public virtual HSBA HSBA { get; set; }
    }
}
